#!/usr/bin/env bash
# Created by Copilot on 2026-03-27
# Shared helpers for Cloud Run deployment automation.

COMMON_LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${COMMON_LIB_DIR}/../../.." && pwd)"
# shellcheck source=../../lib/load-env.sh
source "${REPO_ROOT}/scripts/lib/load-env.sh"
load_root_env
STATE_DIR="${REPO_ROOT}/.tmp/cloud-run"
mkdir -p "${STATE_DIR}"

log_section() {
  printf '\n==> %s\n' "$1" >&2
}

log_info() {
  printf '  • %s\n' "$1" >&2
}

log_warn() {
  printf '  ! %s\n' "$1" >&2
}

fail() {
  printf 'ERROR: %s\n' "$1" >&2
  exit 1
}

require_commands() {
  local cmd
  for cmd in "$@"; do
    command -v "$cmd" >/dev/null 2>&1 || fail "Missing required command: ${cmd}"
  done
}

current_project_id() {
  printf '%s' "${GCP_PROJECT_ID:-${PROJECT_ID:-}}"
}

resolve_project_id() {
  local input="${1:-}"

  if [[ -n "${input}" ]]; then
    printf '%s' "${input}"
    return 0
  fi

  local detected
  detected="$(current_project_id)"
  if [[ -n "${detected}" ]]; then
    printf '%s' "${detected}"
    return 0
  fi

  return 1
}

current_region() {
  printf '%s' "${GCP_REGION:-${REGION:-}}"
}

resolve_region() {
  local input="${1:-}"

  if [[ -n "${input}" ]]; then
    printf '%s' "${input}"
    return 0
  fi

  local detected
  detected="$(current_region)"
  if [[ -n "${detected}" ]]; then
    printf '%s' "${detected}"
    return 0
  fi

  return 1
}

require_cloud_run_env() {
  require_gcp_run_env || exit 1
}

append_env_var() {
  local current="${1:-}"
  local entry="${2:-}"

  if [[ -z "${entry}" ]]; then
    printf '%s' "${current}"
    return 0
  fi

  if [[ -z "${current}" ]]; then
    printf '%s' "${entry}"
  else
    printf '%s,%s' "${current}" "${entry}"
  fi
}

gcloud_service_url() {
  local service_name="$1"
  local region="$2"
  local project_id="$3"

  gcloud run services describe "${service_name}" \
    --project "${project_id}" \
    --region "${region}" \
    --format='value(status.url)' 2>/dev/null || true
}

resolve_project_number() {
  local project_id="$1"

  gcloud projects describe "${project_id}" \
    --format='value(projectNumber)' 2>/dev/null || true
}

resolve_cloud_run_runtime_service_account() {
  local project_id="$1"
  local project_number="$2"

  if [[ -n "${CLOUD_RUN_RUNTIME_SERVICE_ACCOUNT:-}" ]]; then
    printf '%s' "${CLOUD_RUN_RUNTIME_SERVICE_ACCOUNT}"
    return 0
  fi

  if [[ -n "${GOOGLE_SERVICE_ACCOUNT_EMAIL:-}" ]]; then
    printf '%s' "${GOOGLE_SERVICE_ACCOUNT_EMAIL}"
    return 0
  fi

  if [[ -n "${project_number}" ]]; then
    printf '%s-compute@developer.gserviceaccount.com' "${project_number}"
    return 0
  fi

  printf 'default-compute@%s.iam.gserviceaccount.com' "${project_id}"
}

resolve_ces_service_agent() {
  local project_number="$1"
  printf 'service-%s@gcp-sa-ces.iam.gserviceaccount.com' "${project_number}"
}

append_csv_value() {
  local current="${1:-}"
  local entry="${2:-}"

  if [[ -z "${entry}" ]]; then
    printf '%s' "${current}"
    return 0
  fi

  if [[ -z "${current}" ]]; then
    printf '%s' "${entry}"
  else
    printf '%s,%s' "${current}" "${entry}"
  fi
}

service_exists() {
  local service_name="$1"
  local region="$2"
  local project_id="$3"

  gcloud run services describe "${service_name}" \
    --project "${project_id}" \
    --region "${region}" >/dev/null 2>&1
}

write_stack_state() {
  local stack_name="$1"
  local project_id="$2"
  local region="$3"
  local mock_server_url="$4"
  local branch_finder_url="$5"
  local gateway_url="$6"
  local resource_url="$7"
  local state_file="${STATE_DIR}/${stack_name}.env"
  local project_number="${8:-}"
  local runtime_service_account="${9:-}"
  local ces_service_agent="${10:-}"

  cat > "${state_file}" <<EOF
# Generated by scripts/cloud/deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
GCP_PROJECT_ID=${project_id}
PROJECT_ID=${project_id}
GCP_REGION=${region}
REGION=${region}
GCP_PROJECT_NUMBER=${project_number}
CLOUD_RUN_RUNTIME_SERVICE_ACCOUNT=${runtime_service_account}
CES_SERVICE_AGENT_EMAIL=${ces_service_agent}
MOCK_SERVER_URL=${mock_server_url}
BFA_ADAPTER_BRANCH_FINDER_URL=${branch_finder_url}
BFA_GATEWAY_URL=${gateway_url}
BFA_SERVICE_RESOURCE_URL=${resource_url}
EOF

  printf '%s' "${state_file}"
}

