package com.voicebanking.agent.product.integration;

import com.voicebanking.agent.product.domain.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import jakarta.annotation.PostConstruct;
import java.math.BigDecimal;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Mock implementation of ProductCatalogClient for MVP.
 * 
 * Provides realistic product data for Acme Bank products:
 * - 4 Credit Card products (Standard, Gold, Platinum, Business)
 * - 4 Giro Konto products (AktivKonto, BestKonto, Junges Konto, Basiskonto)
 * - 2 Debit Card products (Debit Mastercard, girocard)
 * 
 * @author Augment Agent
 * @since 2026-01-25
 */
@Component
@Profile("!production")
public class MockProductCatalogClient implements ProductCatalogClient {
    private static final Logger log = LoggerFactory.getLogger(MockProductCatalogClient.class);
    
    private final Map<String, Product> products = new ConcurrentHashMap<>();
    private final Map<String, FeeSchedule> feeSchedules = new ConcurrentHashMap<>();
    
    @PostConstruct
    public void init() {
        log.info("Initializing MockProductCatalogClient with Acme Bank products");
        initializeCreditCards();
        initializeGiroKontos();
        initializeDebitCards();
        log.info("Loaded {} products", products.size());
    }
    
    private void initializeCreditCards() {
        // MasterCard Standard
        CreditCardProduct standard = CreditCardProduct.creditCardBuilder()
            .id("cc-standard")
            .nameEn("DB MasterCard Standard")
            .nameDe("DB MasterCard Standard")
            .descriptionEn("Basic credit card with worldwide acceptance")
            .descriptionDe("Basis-Kreditkarte mit weltweiter Akzeptanz")
            .cardNetwork("Mastercard")
            .creditLimitMin(500)
            .creditLimitMax(5000)
            .interestRate(15.9)
            .contactlessEnabled(true)
            .applePaySupported(true)
            .googlePaySupported(true)
            .comparisonGroup("credit-cards-personal")
            .eligibility(EligibilityCriteria.builder()
                .minimumAge(18)
                .requiresAccountWithBank(true)
                .residencyRequirementEn("Residence in Germany")
                .residencyRequirementDe("Wohnsitz in Deutschland")
                .build())
            .addFeature(ProductFeature.builder()
                .id("contactless")
                .nameEn("Contactless Payments")
                .nameDe("Kontaktloses Bezahlen")
                .isHighlight(true)
                .valueEn("Enabled")
                .valueDe("Aktiviert")
                .build())
            .addFeature(ProductFeature.builder()
                .id("mobile-pay")
                .nameEn("Mobile Payment")
                .nameDe("Mobiles Bezahlen")
                .descriptionEn("Apple Pay and Google Pay supported")
                .descriptionDe("Apple Pay und Google Pay unterstützt")
                .isHighlight(true)
                .build())
            .build();
        
        FeeSchedule standardFees = FeeSchedule.builder()
            .productId("cc-standard")
            .productName("DB MasterCard Standard")
            .category(ProductCategory.CREDIT_CARD)
            .effectiveDate("2026-01-01")
            .addFee(Fee.builder()
                .id("annual-fee")
                .nameEn("Annual Fee")
                .nameDe("Jahresgebühr")
                .amount(35.00)
                .currency("EUR")
                .type(FeeType.PERIODIC)
                .frequency(FeeFrequency.ANNUAL)
                .build())
            .addFee(Fee.builder()
                .id("cash-advance")
                .nameEn("Cash Advance Fee")
                .nameDe("Bargeldabhebungsgebühr")
                .amount(3.00)
                .currency("EUR")
                .type(FeeType.TRANSACTION)
                .frequency(FeeFrequency.PER_USE)
                .conditionEn("Minimum €5.00")
                .conditionDe("Mindestens €5,00")
                .build())
            .build();
        
        standard = CreditCardProduct.creditCardBuilder()
            .id(standard.getId())
            .nameEn(standard.getNameEn())
            .nameDe(standard.getNameDe())
            .descriptionEn(standard.getDescriptionEn())
            .descriptionDe(standard.getDescriptionDe())
            .cardNetwork(standard.getCardNetwork())
            .creditLimitMin(standard.getCreditLimitMin())
            .creditLimitMax(standard.getCreditLimitMax())
            .interestRate(standard.getInterestRate())
            .contactlessEnabled(standard.isContactlessEnabled())
            .applePaySupported(standard.isApplePaySupported())
            .googlePaySupported(standard.isGooglePaySupported())
            .comparisonGroup(standard.getComparisonGroup())
            .eligibility(standard.getEligibility())
            .features(standard.getFeatures())
            .feeSchedule(standardFees)
            .build();
        
        products.put("cc-standard", standard);
        feeSchedules.put("cc-standard", standardFees);
        
        // MasterCard Gold
        CreditCardProduct gold = CreditCardProduct.creditCardBuilder()
            .id("cc-gold")
            .nameEn("DB MasterCard Gold")
            .nameDe("DB MasterCard Gold")
            .descriptionEn("Premium credit card with insurance package and higher limits")
            .descriptionDe("Premium-Kreditkarte mit Versicherungspaket und höheren Limits")
            .cardNetwork("Mastercard")
            .creditLimitMin(2500)
            .creditLimitMax(15000)
            .interestRate(14.9)
            .contactlessEnabled(true)
            .applePaySupported(true)
            .googlePaySupported(true)
            .insurancePackage("Travel insurance and purchase protection")
            .comparisonGroup("credit-cards-personal")
            .eligibility(EligibilityCriteria.builder()
                .minimumAge(18)
                .minimumIncome(2000.0)
                .requiresAccountWithBank(true)
                .residencyRequirementEn("Residence in Germany")
                .residencyRequirementDe("Wohnsitz in Deutschland")
                .build())
            .addFeature(ProductFeature.builder()
                .id("travel-insurance")
                .nameEn("Travel Insurance")
                .nameDe("Reiseversicherung")
                .descriptionEn("Comprehensive travel insurance included")
                .descriptionDe("Umfassende Reiseversicherung inklusive")
                .isHighlight(true)
                .valueEn("Included")
                .valueDe("Inklusive")
                .build())
            .addFeature(ProductFeature.builder()
                .id("purchase-protection")
                .nameEn("Purchase Protection")
                .nameDe("Einkaufsschutz")
                .isHighlight(true)
                .valueEn("90 days")
                .valueDe("90 Tage")
                .build())
            .addFeature(ProductFeature.builder()
                .id("lounge-access")
                .nameEn("Airport Lounge Discount")
                .nameDe("Flughafen-Lounge-Rabatt")
                .valueEn("20% off")
                .valueDe("20% Rabatt")
                .build())
            .build();
        
        FeeSchedule goldFees = FeeSchedule.builder()
            .productId("cc-gold")
            .productName("DB MasterCard Gold")
            .category(ProductCategory.CREDIT_CARD)
            .effectiveDate("2026-01-01")
            .addFee(Fee.builder()
                .id("annual-fee")
                .nameEn("Annual Fee")
                .nameDe("Jahresgebühr")
                .amount(80.00)
                .currency("EUR")
                .type(FeeType.PERIODIC)
                .frequency(FeeFrequency.ANNUAL)
                .waiversEn("waived with €3,000 monthly spend")
                .waiversDe("entfällt bei €3.000 monatlichem Umsatz")
                .build())
            .addFee(Fee.builder()
                .id("cash-advance")
                .nameEn("Cash Advance Fee")
                .nameDe("Bargeldabhebungsgebühr")
                .amount(0.00)
                .currency("EUR")
                .type(FeeType.TRANSACTION)
                .frequency(FeeFrequency.PER_USE)
                .conditionEn("4 free withdrawals per month")
                .conditionDe("4 kostenlose Abhebungen pro Monat")
                .build())
            .build();
        
        gold = CreditCardProduct.creditCardBuilder()
            .id(gold.getId())
            .nameEn(gold.getNameEn())
            .nameDe(gold.getNameDe())
            .descriptionEn(gold.getDescriptionEn())
            .descriptionDe(gold.getDescriptionDe())
            .cardNetwork(gold.getCardNetwork())
            .creditLimitMin(gold.getCreditLimitMin())
            .creditLimitMax(gold.getCreditLimitMax())
            .interestRate(gold.getInterestRate())
            .contactlessEnabled(gold.isContactlessEnabled())
            .applePaySupported(gold.isApplePaySupported())
            .googlePaySupported(gold.isGooglePaySupported())
            .insurancePackage(gold.getInsurancePackage())
            .comparisonGroup(gold.getComparisonGroup())
            .eligibility(gold.getEligibility())
            .features(gold.getFeatures())
            .feeSchedule(goldFees)
            .build();
        
        products.put("cc-gold", gold);
        feeSchedules.put("cc-gold", goldFees);
        
        // MasterCard Platinum
        CreditCardProduct platinum = CreditCardProduct.creditCardBuilder()
            .id("cc-platinum")
            .nameEn("DB MasterCard Platinum")
            .nameDe("DB MasterCard Platinum")
            .descriptionEn("Exclusive credit card with premium benefits and concierge service")
            .descriptionDe("Exklusive Kreditkarte mit Premium-Vorteilen und Concierge-Service")
            .cardNetwork("Mastercard")
            .creditLimitMin(10000)
            .creditLimitMax(50000)
            .interestRate(13.9)
            .contactlessEnabled(true)
            .applePaySupported(true)
            .googlePaySupported(true)
            .insurancePackage("Comprehensive travel, medical, and purchase protection")
            .rewardsProgram("2% cashback on all purchases")
            .comparisonGroup("credit-cards-personal")
            .eligibility(EligibilityCriteria.builder()
                .minimumAge(18)
                .minimumIncome(5000.0)
                .requiresAccountWithBank(true)
                .residencyRequirementEn("Residence in Germany")
                .residencyRequirementDe("Wohnsitz in Deutschland")
                .build())
            .addFeature(ProductFeature.builder()
                .id("concierge")
                .nameEn("24/7 Concierge Service")
                .nameDe("24/7 Concierge-Service")
                .isHighlight(true)
                .valueEn("Included")
                .valueDe("Inklusive")
                .build())
            .addFeature(ProductFeature.builder()
                .id("lounge-access")
                .nameEn("Airport Lounge Access")
                .nameDe("Flughafen-Lounge-Zugang")
                .isHighlight(true)
                .valueEn("Unlimited")
                .valueDe("Unbegrenzt")
                .build())
            .addFeature(ProductFeature.builder()
                .id("cashback")
                .nameEn("Cashback")
                .nameDe("Cashback")
                .isHighlight(true)
                .valueEn("2% on all purchases")
                .valueDe("2% auf alle Einkäufe")
                .build())
            .build();
        
        FeeSchedule platinumFees = FeeSchedule.builder()
            .productId("cc-platinum")
            .productName("DB MasterCard Platinum")
            .category(ProductCategory.CREDIT_CARD)
            .effectiveDate("2026-01-01")
            .addFee(Fee.builder()
                .id("annual-fee")
                .nameEn("Annual Fee")
                .nameDe("Jahresgebühr")
                .amount(180.00)
                .currency("EUR")
                .type(FeeType.PERIODIC)
                .frequency(FeeFrequency.ANNUAL)
                .build())
            .addFee(Fee.builder()
                .id("cash-advance")
                .nameEn("Cash Advance Fee")
                .nameDe("Bargeldabhebungsgebühr")
                .amount(0.00)
                .currency("EUR")
                .type(FeeType.TRANSACTION)
                .frequency(FeeFrequency.PER_USE)
                .conditionEn("Unlimited free withdrawals worldwide")
                .conditionDe("Unbegrenzte kostenlose Abhebungen weltweit")
                .build())
            .build();
        
        platinum = CreditCardProduct.creditCardBuilder()
            .id(platinum.getId())
            .nameEn(platinum.getNameEn())
            .nameDe(platinum.getNameDe())
            .descriptionEn(platinum.getDescriptionEn())
            .descriptionDe(platinum.getDescriptionDe())
            .cardNetwork(platinum.getCardNetwork())
            .creditLimitMin(platinum.getCreditLimitMin())
            .creditLimitMax(platinum.getCreditLimitMax())
            .interestRate(platinum.getInterestRate())
            .contactlessEnabled(platinum.isContactlessEnabled())
            .applePaySupported(platinum.isApplePaySupported())
            .googlePaySupported(platinum.isGooglePaySupported())
            .insurancePackage(platinum.getInsurancePackage())
            .rewardsProgram(platinum.getRewardsProgram())
            .comparisonGroup(platinum.getComparisonGroup())
            .eligibility(platinum.getEligibility())
            .features(platinum.getFeatures())
            .feeSchedule(platinumFees)
            .build();
        
        products.put("cc-platinum", platinum);
        feeSchedules.put("cc-platinum", platinumFees);
        
        // Business Card
        CreditCardProduct business = CreditCardProduct.creditCardBuilder()
            .id("cc-business")
            .nameEn("DB Business Card")
            .nameDe("DB Business Card")
            .descriptionEn("Corporate credit card for business expenses")
            .descriptionDe("Firmenkreditkarte für Geschäftsausgaben")
            .cardNetwork("Mastercard")
            .creditLimitMin(5000)
            .creditLimitMax(100000)
            .interestRate(12.9)
            .contactlessEnabled(true)
            .applePaySupported(true)
            .googlePaySupported(true)
            .comparisonGroup("credit-cards-business")
            .eligibility(EligibilityCriteria.builder()
                .minimumAge(18)
                .requiresAccountWithBank(true)
                .addRequirementEn("Registered business in Germany")
                .addRequirementDe("Eingetragenes Unternehmen in Deutschland")
                .build())
            .addFeature(ProductFeature.builder()
                .id("expense-reporting")
                .nameEn("Expense Reporting")
                .nameDe("Spesenabrechnung")
                .isHighlight(true)
                .valueEn("Automated")
                .valueDe("Automatisiert")
                .build())
            .addFeature(ProductFeature.builder()
                .id("employee-cards")
                .nameEn("Employee Cards")
                .nameDe("Mitarbeiterkarten")
                .isHighlight(true)
                .valueEn("Up to 10 included")
                .valueDe("Bis zu 10 inklusive")
                .build())
            .build();
        
        FeeSchedule businessFees = FeeSchedule.builder()
            .productId("cc-business")
            .productName("DB Business Card")
            .category(ProductCategory.CREDIT_CARD)
            .effectiveDate("2026-01-01")
            .addFee(Fee.builder()
                .id("annual-fee")
                .nameEn("Annual Fee")
                .nameDe("Jahresgebühr")
                .amount(120.00)
                .currency("EUR")
                .type(FeeType.PERIODIC)
                .frequency(FeeFrequency.ANNUAL)
                .conditionEn("Per main card, employee cards €30 each")
                .conditionDe("Pro Hauptkarte, Mitarbeiterkarten je €30")
                .build())
            .build();
        
        business = CreditCardProduct.creditCardBuilder()
            .id(business.getId())
            .nameEn(business.getNameEn())
            .nameDe(business.getNameDe())
            .descriptionEn(business.getDescriptionEn())
            .descriptionDe(business.getDescriptionDe())
            .cardNetwork(business.getCardNetwork())
            .creditLimitMin(business.getCreditLimitMin())
            .creditLimitMax(business.getCreditLimitMax())
            .interestRate(business.getInterestRate())
            .contactlessEnabled(business.isContactlessEnabled())
            .applePaySupported(business.isApplePaySupported())
            .googlePaySupported(business.isGooglePaySupported())
            .comparisonGroup(business.getComparisonGroup())
            .eligibility(business.getEligibility())
            .features(business.getFeatures())
            .feeSchedule(businessFees)
            .build();
        
        products.put("cc-business", business);
        feeSchedules.put("cc-business", businessFees);
    }
    
    private void initializeGiroKontos() {
        // AktivKonto
        GiroKontoProduct aktiv = GiroKontoProduct.giroKontoBuilder()
            .id("gk-aktiv")
            .nameEn("AktivKonto")
            .nameDe("AktivKonto")
            .descriptionEn("Standard checking account for everyday banking")
            .descriptionDe("Standard-Girokonto für den täglichen Zahlungsverkehr")
            .includedTransactionsPerMonth(null) // Unlimited
            .debitCardIncluded(true)
            .debitCardType("Debit Mastercard")
            .freeAtmWithdrawals(5)
            .overdraftInterestRate(10.85)
            .comparisonGroup("giro-konten")
            .targetAudienceEn("Adults seeking a reliable everyday account")
            .targetAudienceDe("Erwachsene, die ein zuverlässiges Alltagskonto suchen")
            .eligibility(EligibilityCriteria.builder()
                .minimumAge(18)
                .residencyRequirementEn("Residence in Germany")
                .residencyRequirementDe("Wohnsitz in Deutschland")
                .build())
            .addFeature(ProductFeature.builder()
                .id("online-banking")
                .nameEn("Online Banking")
                .nameDe("Online-Banking")
                .isHighlight(true)
                .valueEn("Included")
                .valueDe("Inklusive")
                .build())
            .addFeature(ProductFeature.builder()
                .id("mobile-app")
                .nameEn("Mobile Banking App")
                .nameDe("Mobile-Banking-App")
                .isHighlight(true)
                .valueEn("Included")
                .valueDe("Inklusive")
                .build())
            .build();
        
        FeeSchedule aktivFees = FeeSchedule.builder()
            .productId("gk-aktiv")
            .productName("AktivKonto")
            .category(ProductCategory.GIRO_KONTO)
            .effectiveDate("2026-01-01")
            .addFee(Fee.builder()
                .id("monthly-fee")
                .nameEn("Monthly Fee")
                .nameDe("Monatliche Kontoführungsgebühr")
                .amount(6.90)
                .currency("EUR")
                .type(FeeType.PERIODIC)
                .frequency(FeeFrequency.MONTHLY)
                .waiversEn("waived with €1,200 monthly income deposit")
                .waiversDe("entfällt bei €1.200 monatlichem Gehaltseingang")
                .build())
            .addFee(Fee.builder()
                .id("atm-withdrawal")
                .nameEn("ATM Withdrawal (after free limit)")
                .nameDe("Geldautomat (nach Freigrenze)")
                .amount(1.50)
                .currency("EUR")
                .type(FeeType.TRANSACTION)
                .frequency(FeeFrequency.PER_USE)
                .conditionEn("After 5 free withdrawals per month")
                .conditionDe("Nach 5 kostenlosen Abhebungen pro Monat")
                .build())
            .build();
        
        aktiv = GiroKontoProduct.giroKontoBuilder()
            .id(aktiv.getId())
            .nameEn(aktiv.getNameEn())
            .nameDe(aktiv.getNameDe())
            .descriptionEn(aktiv.getDescriptionEn())
            .descriptionDe(aktiv.getDescriptionDe())
            .includedTransactionsPerMonth(aktiv.getIncludedTransactionsPerMonth())
            .debitCardIncluded(aktiv.isDebitCardIncluded())
            .debitCardType(aktiv.getDebitCardType())
            .freeAtmWithdrawals(aktiv.getFreeAtmWithdrawals())
            .overdraftInterestRate(aktiv.getOverdraftInterestRate())
            .comparisonGroup(aktiv.getComparisonGroup())
            .targetAudienceEn(aktiv.getTargetAudienceEn())
            .targetAudienceDe(aktiv.getTargetAudienceDe())
            .eligibility(aktiv.getEligibility())
            .features(aktiv.getFeatures())
            .feeSchedule(aktivFees)
            .build();
        
        products.put("gk-aktiv", aktiv);
        feeSchedules.put("gk-aktiv", aktivFees);
        
        // BestKonto
        GiroKontoProduct best = GiroKontoProduct.giroKontoBuilder()
            .id("gk-best")
            .nameEn("BestKonto")
            .nameDe("BestKonto")
            .descriptionEn("Premium checking account with extra benefits")
            .descriptionDe("Premium-Girokonto mit zusätzlichen Vorteilen")
            .includedTransactionsPerMonth(null) // Unlimited
            .debitCardIncluded(true)
            .debitCardType("Debit Mastercard Gold")
            .freeAtmWithdrawals(null) // Unlimited
            .overdraftInterestRate(9.85)
            .comparisonGroup("giro-konten")
            .targetAudienceEn("Customers wanting premium banking features")
            .targetAudienceDe("Kunden, die Premium-Banking-Funktionen wünschen")
            .eligibility(EligibilityCriteria.builder()
                .minimumAge(18)
                .residencyRequirementEn("Residence in Germany")
                .residencyRequirementDe("Wohnsitz in Deutschland")
                .build())
            .addFeature(ProductFeature.builder()
                .id("unlimited-atm")
                .nameEn("Unlimited ATM Withdrawals")
                .nameDe("Unbegrenzte Geldautomaten-Abhebungen")
                .isHighlight(true)
                .valueEn("Free worldwide")
                .valueDe("Weltweit kostenlos")
                .build())
            .addFeature(ProductFeature.builder()
                .id("travel-insurance")
                .nameEn("Travel Insurance")
                .nameDe("Reiseversicherung")
                .isHighlight(true)
                .valueEn("Included")
                .valueDe("Inklusive")
                .build())
            .addFeature(ProductFeature.builder()
                .id("instant-transfers")
                .nameEn("Instant Transfers")
                .nameDe("Echtzeitüberweisungen")
                .isHighlight(true)
                .valueEn("Free")
                .valueDe("Kostenlos")
                .build())
            .build();
        
        FeeSchedule bestFees = FeeSchedule.builder()
            .productId("gk-best")
            .productName("BestKonto")
            .category(ProductCategory.GIRO_KONTO)
            .effectiveDate("2026-01-01")
            .addFee(Fee.builder()
                .id("monthly-fee")
                .nameEn("Monthly Fee")
                .nameDe("Monatliche Kontoführungsgebühr")
                .amount(12.90)
                .currency("EUR")
                .type(FeeType.PERIODIC)
                .frequency(FeeFrequency.MONTHLY)
                .build())
            .build();
        
        best = GiroKontoProduct.giroKontoBuilder()
            .id(best.getId())
            .nameEn(best.getNameEn())
            .nameDe(best.getNameDe())
            .descriptionEn(best.getDescriptionEn())
            .descriptionDe(best.getDescriptionDe())
            .includedTransactionsPerMonth(best.getIncludedTransactionsPerMonth())
            .debitCardIncluded(best.isDebitCardIncluded())
            .debitCardType(best.getDebitCardType())
            .freeAtmWithdrawals(best.getFreeAtmWithdrawals())
            .overdraftInterestRate(best.getOverdraftInterestRate())
            .comparisonGroup(best.getComparisonGroup())
            .targetAudienceEn(best.getTargetAudienceEn())
            .targetAudienceDe(best.getTargetAudienceDe())
            .eligibility(best.getEligibility())
            .features(best.getFeatures())
            .feeSchedule(bestFees)
            .build();
        
        products.put("gk-best", best);
        feeSchedules.put("gk-best", bestFees);
        
        // Junges Konto (Youth Account)
        GiroKontoProduct junges = GiroKontoProduct.giroKontoBuilder()
            .id("gk-junges")
            .nameEn("Junges Konto")
            .nameDe("Junges Konto")
            .descriptionEn("Free checking account for students and young adults (18-30)")
            .descriptionDe("Kostenloses Girokonto für Studenten und junge Erwachsene (18-30)")
            .includedTransactionsPerMonth(null)
            .debitCardIncluded(true)
            .debitCardType("Debit Mastercard")
            .freeAtmWithdrawals(null)
            .overdraftInterestRate(10.85)
            .comparisonGroup("giro-konten")
            .targetAudienceEn("Students and young adults aged 18-30")
            .targetAudienceDe("Studenten und junge Erwachsene im Alter von 18-30")
            .eligibility(EligibilityCriteria.builder()
                .minimumAge(18)
                .maximumAge(30)
                .residencyRequirementEn("Residence in Germany")
                .residencyRequirementDe("Wohnsitz in Deutschland")
                .addRequirementEn("Student ID or proof of age")
                .addRequirementDe("Studentenausweis oder Altersnachweis")
                .build())
            .addFeature(ProductFeature.builder()
                .id("no-fee")
                .nameEn("No Monthly Fee")
                .nameDe("Keine Kontoführungsgebühr")
                .isHighlight(true)
                .valueEn("€0")
                .valueDe("€0")
                .build())
            .addFeature(ProductFeature.builder()
                .id("free-withdrawals")
                .nameEn("Free ATM Withdrawals")
                .nameDe("Kostenlose Geldautomaten-Abhebungen")
                .isHighlight(true)
                .valueEn("Unlimited in Germany")
                .valueDe("Unbegrenzt in Deutschland")
                .build())
            .build();
        
        FeeSchedule jungesFees = FeeSchedule.builder()
            .productId("gk-junges")
            .productName("Junges Konto")
            .category(ProductCategory.GIRO_KONTO)
            .effectiveDate("2026-01-01")
            .addFee(Fee.builder()
                .id("monthly-fee")
                .nameEn("Monthly Fee")
                .nameDe("Monatliche Kontoführungsgebühr")
                .amount(0.00)
                .currency("EUR")
                .type(FeeType.PERIODIC)
                .frequency(FeeFrequency.MONTHLY)
                .conditionEn("Free for customers aged 18-30")
                .conditionDe("Kostenlos für Kunden im Alter von 18-30")
                .build())
            .build();
        
        junges = GiroKontoProduct.giroKontoBuilder()
            .id(junges.getId())
            .nameEn(junges.getNameEn())
            .nameDe(junges.getNameDe())
            .descriptionEn(junges.getDescriptionEn())
            .descriptionDe(junges.getDescriptionDe())
            .includedTransactionsPerMonth(junges.getIncludedTransactionsPerMonth())
            .debitCardIncluded(junges.isDebitCardIncluded())
            .debitCardType(junges.getDebitCardType())
            .freeAtmWithdrawals(junges.getFreeAtmWithdrawals())
            .overdraftInterestRate(junges.getOverdraftInterestRate())
            .comparisonGroup(junges.getComparisonGroup())
            .targetAudienceEn(junges.getTargetAudienceEn())
            .targetAudienceDe(junges.getTargetAudienceDe())
            .eligibility(junges.getEligibility())
            .features(junges.getFeatures())
            .feeSchedule(jungesFees)
            .build();
        
        products.put("gk-junges", junges);
        feeSchedules.put("gk-junges", jungesFees);
        
        // Basiskonto (Basic Account - legally required)
        GiroKontoProduct basis = GiroKontoProduct.giroKontoBuilder()
            .id("gk-basis")
            .nameEn("Basiskonto")
            .nameDe("Basiskonto")
            .descriptionEn("Basic payment account as required by law")
            .descriptionDe("Basiszahlungskonto nach gesetzlicher Vorgabe")
            .includedTransactionsPerMonth(null)
            .debitCardIncluded(true)
            .debitCardType("girocard")
            .freeAtmWithdrawals(3)
            .overdraftInterestRate(null) // No overdraft
            .comparisonGroup("giro-konten")
            .targetAudienceEn("Anyone needing a basic payment account")
            .targetAudienceDe("Jeder, der ein Basiszahlungskonto benötigt")
            .eligibility(EligibilityCriteria.builder()
                .minimumAge(18)
                .residencyRequirementEn("Legal residence in the EU")
                .residencyRequirementDe("Rechtmäßiger Aufenthalt in der EU")
                .build())
            .addFeature(ProductFeature.builder()
                .id("legal-right")
                .nameEn("Legal Right to Account")
                .nameDe("Gesetzlicher Kontoanspruch")
                .descriptionEn("Everyone has a right to a basic payment account")
                .descriptionDe("Jeder hat Anspruch auf ein Basiszahlungskonto")
                .isHighlight(true)
                .build())
            .build();
        
        FeeSchedule basisFees = FeeSchedule.builder()
            .productId("gk-basis")
            .productName("Basiskonto")
            .category(ProductCategory.GIRO_KONTO)
            .effectiveDate("2026-01-01")
            .addFee(Fee.builder()
                .id("monthly-fee")
                .nameEn("Monthly Fee")
                .nameDe("Monatliche Kontoführungsgebühr")
                .amount(8.99)
                .currency("EUR")
                .type(FeeType.PERIODIC)
                .frequency(FeeFrequency.MONTHLY)
                .build())
            .addFee(Fee.builder()
                .id("atm-withdrawal")
                .nameEn("ATM Withdrawal (after free limit)")
                .nameDe("Geldautomat (nach Freigrenze)")
                .amount(2.00)
                .currency("EUR")
                .type(FeeType.TRANSACTION)
                .frequency(FeeFrequency.PER_USE)
                .conditionEn("After 3 free withdrawals per month")
                .conditionDe("Nach 3 kostenlosen Abhebungen pro Monat")
                .build())
            .build();
        
        basis = GiroKontoProduct.giroKontoBuilder()
            .id(basis.getId())
            .nameEn(basis.getNameEn())
            .nameDe(basis.getNameDe())
            .descriptionEn(basis.getDescriptionEn())
            .descriptionDe(basis.getDescriptionDe())
            .includedTransactionsPerMonth(basis.getIncludedTransactionsPerMonth())
            .debitCardIncluded(basis.isDebitCardIncluded())
            .debitCardType(basis.getDebitCardType())
            .freeAtmWithdrawals(basis.getFreeAtmWithdrawals())
            .overdraftInterestRate(basis.getOverdraftInterestRate())
            .comparisonGroup(basis.getComparisonGroup())
            .targetAudienceEn(basis.getTargetAudienceEn())
            .targetAudienceDe(basis.getTargetAudienceDe())
            .eligibility(basis.getEligibility())
            .features(basis.getFeatures())
            .feeSchedule(basisFees)
            .build();
        
        products.put("gk-basis", basis);
        feeSchedules.put("gk-basis", basisFees);
    }
    
    private void initializeDebitCards() {
        // Debit Mastercard
        DebitCardProduct debitMc = DebitCardProduct.debitCardBuilder()
            .id("dc-mastercard")
            .nameEn("Debit Mastercard")
            .nameDe("Debit Mastercard")
            .descriptionEn("Modern debit card with worldwide acceptance")
            .descriptionDe("Moderne Debitkarte mit weltweiter Akzeptanz")
            .cardNetwork("Mastercard")
            .dailyWithdrawalLimit(1000)
            .dailyPurchaseLimit(2500)
            .contactlessEnabled(true)
            .contactlessLimit(50)
            .onlinePaymentsEnabled(true)
            .applePaySupported(true)
            .googlePaySupported(true)
            .instantNotifications(true)
            .comparisonGroup("debit-cards")
            .bundledWithProductId("gk-aktiv")
            .eligibility(EligibilityCriteria.builder()
                .minimumAge(18)
                .requiresAccountWithBank(true)
                .build())
            .addFeature(ProductFeature.builder()
                .id("worldwide")
                .nameEn("Worldwide Acceptance")
                .nameDe("Weltweite Akzeptanz")
                .isHighlight(true)
                .valueEn("50+ million locations")
                .valueDe("50+ Millionen Standorte")
                .build())
            .addFeature(ProductFeature.builder()
                .id("instant-notify")
                .nameEn("Instant Notifications")
                .nameDe("Sofortbenachrichtigungen")
                .isHighlight(true)
                .valueEn("Every transaction")
                .valueDe("Jede Transaktion")
                .build())
            .build();
        
        FeeSchedule debitMcFees = FeeSchedule.builder()
            .productId("dc-mastercard")
            .productName("Debit Mastercard")
            .category(ProductCategory.DEBIT_CARD)
            .effectiveDate("2026-01-01")
            .addFee(Fee.builder()
                .id("card-fee")
                .nameEn("Card Fee")
                .nameDe("Kartengebühr")
                .amount(0.00)
                .currency("EUR")
                .type(FeeType.PERIODIC)
                .frequency(FeeFrequency.ANNUAL)
                .conditionEn("Included with account")
                .conditionDe("Im Konto enthalten")
                .build())
            .addFee(Fee.builder()
                .id("replacement")
                .nameEn("Replacement Card")
                .nameDe("Ersatzkarte")
                .amount(15.00)
                .currency("EUR")
                .type(FeeType.SERVICE)
                .frequency(FeeFrequency.ONE_TIME)
                .build())
            .build();
        
        debitMc = DebitCardProduct.debitCardBuilder()
            .id(debitMc.getId())
            .nameEn(debitMc.getNameEn())
            .nameDe(debitMc.getNameDe())
            .descriptionEn(debitMc.getDescriptionEn())
            .descriptionDe(debitMc.getDescriptionDe())
            .cardNetwork(debitMc.getCardNetwork())
            .dailyWithdrawalLimit(debitMc.getDailyWithdrawalLimit())
            .dailyPurchaseLimit(debitMc.getDailyPurchaseLimit())
            .contactlessEnabled(debitMc.isContactlessEnabled())
            .contactlessLimit(debitMc.getContactlessLimit())
            .onlinePaymentsEnabled(debitMc.isOnlinePaymentsEnabled())
            .applePaySupported(debitMc.isApplePaySupported())
            .googlePaySupported(debitMc.isGooglePaySupported())
            .instantNotifications(debitMc.isInstantNotifications())
            .comparisonGroup(debitMc.getComparisonGroup())
            .bundledWithProductId(debitMc.getBundledWithProductId())
            .eligibility(debitMc.getEligibility())
            .features(debitMc.getFeatures())
            .feeSchedule(debitMcFees)
            .build();
        
        products.put("dc-mastercard", debitMc);
        feeSchedules.put("dc-mastercard", debitMcFees);
        
        // girocard
        DebitCardProduct girocard = DebitCardProduct.debitCardBuilder()
            .id("dc-girocard")
            .nameEn("girocard")
            .nameDe("girocard")
            .descriptionEn("Traditional German debit card for domestic use")
            .descriptionDe("Traditionelle deutsche Debitkarte für den Inlandsgebrauch")
            .cardNetwork("girocard")
            .dailyWithdrawalLimit(1000)
            .dailyPurchaseLimit(2000)
            .contactlessEnabled(true)
            .contactlessLimit(50)
            .onlinePaymentsEnabled(false)
            .applePaySupported(false)
            .googlePaySupported(false)
            .instantNotifications(true)
            .comparisonGroup("debit-cards")
            .bundledWithProductId("gk-basis")
            .eligibility(EligibilityCriteria.builder()
                .minimumAge(18)
                .requiresAccountWithBank(true)
                .build())
            .addFeature(ProductFeature.builder()
                .id("german-acceptance")
                .nameEn("German Acceptance")
                .nameDe("Akzeptanz in Deutschland")
                .isHighlight(true)
                .valueEn("Accepted everywhere in Germany")
                .valueDe("Überall in Deutschland akzeptiert")
                .build())
            .addFeature(ProductFeature.builder()
                .id("contactless")
                .nameEn("Contactless")
                .nameDe("Kontaktlos")
                .isHighlight(true)
                .valueEn("Up to €50 without PIN")
                .valueDe("Bis €50 ohne PIN")
                .build())
            .build();
        
        FeeSchedule girocardFees = FeeSchedule.builder()
            .productId("dc-girocard")
            .productName("girocard")
            .category(ProductCategory.DEBIT_CARD)
            .effectiveDate("2026-01-01")
            .addFee(Fee.builder()
                .id("card-fee")
                .nameEn("Card Fee")
                .nameDe("Kartengebühr")
                .amount(0.00)
                .currency("EUR")
                .type(FeeType.PERIODIC)
                .frequency(FeeFrequency.ANNUAL)
                .conditionEn("Included with account")
                .conditionDe("Im Konto enthalten")
                .build())
            .addFee(Fee.builder()
                .id("replacement")
                .nameEn("Replacement Card")
                .nameDe("Ersatzkarte")
                .amount(10.00)
                .currency("EUR")
                .type(FeeType.SERVICE)
                .frequency(FeeFrequency.ONE_TIME)
                .build())
            .build();
        
        girocard = DebitCardProduct.debitCardBuilder()
            .id(girocard.getId())
            .nameEn(girocard.getNameEn())
            .nameDe(girocard.getNameDe())
            .descriptionEn(girocard.getDescriptionEn())
            .descriptionDe(girocard.getDescriptionDe())
            .cardNetwork(girocard.getCardNetwork())
            .dailyWithdrawalLimit(girocard.getDailyWithdrawalLimit())
            .dailyPurchaseLimit(girocard.getDailyPurchaseLimit())
            .contactlessEnabled(girocard.isContactlessEnabled())
            .contactlessLimit(girocard.getContactlessLimit())
            .onlinePaymentsEnabled(girocard.isOnlinePaymentsEnabled())
            .applePaySupported(girocard.isApplePaySupported())
            .googlePaySupported(girocard.isGooglePaySupported())
            .instantNotifications(girocard.isInstantNotifications())
            .comparisonGroup(girocard.getComparisonGroup())
            .bundledWithProductId(girocard.getBundledWithProductId())
            .eligibility(girocard.getEligibility())
            .features(girocard.getFeatures())
            .feeSchedule(girocardFees)
            .build();
        
        products.put("dc-girocard", girocard);
        feeSchedules.put("dc-girocard", girocardFees);
    }
    
    @Override
    public List<Product> getProductsByCategory(ProductCategory category) {
        return products.values().stream()
            .filter(p -> p.getCategory() == category)
            .filter(Product::isActive)
            .toList();
    }
    
    @Override
    public List<CreditCardProduct> getCreditCardProducts() {
        return products.values().stream()
            .filter(p -> p instanceof CreditCardProduct)
            .filter(Product::isActive)
            .map(p -> (CreditCardProduct) p)
            .toList();
    }
    
    @Override
    public List<GiroKontoProduct> getGiroKontoProducts() {
        return products.values().stream()
            .filter(p -> p instanceof GiroKontoProduct)
            .filter(Product::isActive)
            .map(p -> (GiroKontoProduct) p)
            .toList();
    }
    
    @Override
    public List<DebitCardProduct> getDebitCardProducts() {
        return products.values().stream()
            .filter(p -> p instanceof DebitCardProduct)
            .filter(Product::isActive)
            .map(p -> (DebitCardProduct) p)
            .toList();
    }
    
    @Override
    public Optional<Product> getProductById(String productId) {
        return Optional.ofNullable(products.get(productId));
    }
    
    @Override
    public Optional<FeeSchedule> getFeeSchedule(String productId) {
        return Optional.ofNullable(feeSchedules.get(productId));
    }
    
    @Override
    public Optional<EligibilityCriteria> getEligibility(String productId) {
        return getProductById(productId)
            .map(Product::getEligibility);
    }
    
    @Override
    public boolean areProductsComparable(String productId1, String productId2) {
        Optional<Product> p1 = getProductById(productId1);
        Optional<Product> p2 = getProductById(productId2);
        
        if (p1.isEmpty() || p2.isEmpty()) {
            return false;
        }
        
        String group1 = p1.get().getComparisonGroup();
        String group2 = p2.get().getComparisonGroup();
        
        return group1 != null && group1.equals(group2);
    }
}
